TMP add secretstream
c4dt/nacl-compat pull request #1
Opened 2021-07-28 11:45 UTC by tharvik

2021-07-30 05:59 UTC, ineiti commented on crypto_secretstream/Cargo.toml
> +rand_core = { version = "0.6", features = ["std"] }
Newbie question: in another crypto project I saw that they're using `rand`. Does rustcrypto prefer `rand_core`? Can you point out the differences?

2021-07-30 06:33 UTC, ineiti requested changes
That was fast! Great work.

I would really like to have an integration test with libsodium here.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/key.rs
> +    pub const SIZE: usize = 32;
Is there some constant available for this `32`? Somewhere in the XChaCha-crate?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/key.rs
> +    pub fn to_bytes(&self) -> [u8; Key::SIZE] {
Does this return a copy of the key?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! key (such as one generated via a key exchange protocol), then she open an
```suggestion
//! key (such as one generated via a key exchange protocol), then she opens a
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! normal/unsafe channel of communication and send her messages, encrypted
```suggestion
//! normal/unsafe channel of communication and sends her messages, encrypted
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! Under the hood, the first message is postfixed with a random number,
Is the `random number` the `nonce`? If yes, then write so.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! It also allow for additional data to be send with each message.
```suggestion
//! It also allows for additional data to be sent with each message.
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! This data is not encrypted but used in the encryption process thus is needed
```suggestion
//! This data is not encrypted but used in the encryption process thus it is needed
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! to be known in advance from the receiver.
```suggestion
//! to be known in advance by the receiver.
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! contains the plaintext for encryption or ciphertext for decryption.
This is not clear to me and needs to be rewritten.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/nonce.rs
> +    pub const SIZE: usize = 24;
Same as keylength: is there a constant in chacha20 available?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/nonce.rs
> +        // handle overflow
This is something worth mentioning in the documentation of the `Nonce` structure or in the `increase` method.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/pull.rs
> +    /// Decrypt a buffer filled with a pushed message, and its associated data
This should mention that the buffer is overwritten with the decrypted message.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/pull.rs
> +
The C-code also checks the maximum length - from what I can gather, this is something like 256GB:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretstream/xchacha20poly1305/secretstream_xchacha20poly1305.c#L128
and
https://github.com/jedisct1/libsodium/blob/6d566070b48efd2fa099bbe9822914455150aba9/src/libsodium/include/sodium/crypto_secretstream_xchacha20poly1305.h

So I'm not sure whether this should be checked here, too. As contrary to the C-code, you don't have to pass the size of the buffer here.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/pull.rs
> +    /// Decrypt a pushed message, with its associated data
This should mention that it creates a new buffer.

Rust-newbie question: why does it take an array of `u8` but returns a `Vec<u8>`?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/Cargo.toml
> +snafu = "0.6"
Consistency question: is this the same as the other crate in nacl-compat is using for error-handling?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/push.rs
> +    /// Create new stream for sending messages with a preshared key
```suggestion
    /// Create new stream for sending messages with a preshared key.
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/push.rs
> +    /// The RNG is needed to generate a nonce
```suggestion
    /// The RNG is needed to generate a nonce.
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/push.rs
> +    /// Encrypt a buffer filled with a message, and its associated data
```suggestion
    /// Encrypt a buffer filled with a message and its associated data.
```

Also mention that the buffer will be overwritten with the encrypted data.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/push.rs
> +                };
```suggestion
                // add header
                buffer
                    .extend_from_slice(nonce.clone().as_array())
                    .ok()
                    .context(Encrypt)?;

                nonce.increase();
                self.0 = State::Running {
                    nonce,
                    aead,
                };
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/src/push.rs
> +    /// Encrypt a message, with its associated data
Should mention it allocates a new buffer.

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +const KEY: [u8; Key::SIZE] = [
Where do these test-vectors come from?

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +fn two_pushstream_dont_generate_same_ciphertext() {
```suggestion
fn two_pushstreams_dont_generate_same_ciphertext() {
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +fn pushstream_dont_generate_same_ciphertext_for_same_plaintext() {
```suggestion
fn pushstream_doesnt_generate_same_ciphertext_for_same_plaintext() {
```

2021-07-30 06:33 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +
The C implementation has a lot more tests, but I think most of them are related to XChaCha20:

https://github.com/jedisct1/libsodium/blob/master/test/default/secretstream_xchacha20poly1305.c

Can you check if there is something to be tested?

2021-07-30 08:59 UTC, tharvik commented on crypto_secretstream/src/key.rs
> +    pub const SIZE: usize = 32;
I didn't find any, [`chacha20poly1305::Key` is in fact a generic array](https://docs.rs/chacha20poly1305/0.8.1/chacha20poly1305/type.Key.html), where its size is in the type and not as a value.
Anyway, that not really an issue as when changed to 31, it actuallty fails to build
```
error[E0308]: mismatched types
  --> crypto_secretstream/src/pull.rs:55:51
   |
55 |                 let aead = XChaCha20Poly1305::new(&GenericArray::from(key.to_bytes()));
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `UInt`, found struct `UTerm`
   |
   = note: expected reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>`
              found reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B1>, B1>, B1>>`

error[E0308]: mismatched types
  --> crypto_secretstream/src/push.rs:53:51
   |
53 |                 let aead = XChaCha20Poly1305::new(&GenericArray::from(key.to_bytes()));
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `UInt`, found struct `UTerm`
   |
   = note: expected reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>>`
              found reference `&GenericArray<u8, UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B1>, B1>, B1>>`
```

2021-07-30 09:01 UTC, tharvik commented on crypto_secretstream/src/key.rs
> +    pub fn to_bytes(&self) -> [u8; Key::SIZE] {
It does indeed, as arrays implements the `Copy` trait.

2021-07-30 09:04 UTC, tharvik commented on crypto_secretstream/src/nonce.rs
> +    pub const SIZE: usize = 24;
Same as for `Key::SIZE`: It is also implemented as a generic array

2021-07-30 09:13 UTC, tharvik commented on crypto_secretstream/src/pull.rs
> +
It is [already checked by chachapoly1305](https://github.com/RustCrypto/AEADs/blob/master/chacha20poly1305/src/cipher.rs#L55)

2021-07-30 09:21 UTC, tharvik commented on crypto_secretstream/Cargo.toml
> +snafu = "0.6"
`crypto_box` doesnt't use any library for errors, it simply returns `xsalsa20poly1305::aead::Error`.
Hum, in `crypto_secretstream`, it is only really used for when the header is of the wrong size (which doesn't leak any information as the size is known). And yeah, it's overkill to use it only for that; removing it, thanks :)

2021-07-30 09:25 UTC, tharvik commented on crypto_secretstream/tests/lib.rs
> +const KEY: [u8; Key::SIZE] = [
There are mostly taken from `crypto_box`'s tests, it can be generated on-the-fly but I learned a few years ago not to make too random tests.

2021-07-30 09:56 UTC, tharvik commented on crypto_secretstream/src/push.rs
> +                };
It doesn't work. `nonce` is a reference, not a value, so it needs to be cloned to be put in `State::Running`.

2021-07-30 10:37 UTC, ineiti commented on crypto_secretstream/src/key.rs
> +    pub const SIZE: usize = 32;
So if I understand correctly, ChaCha20 has a `Key` defined, so couldn't you use it here?

2021-07-30 10:47 UTC, ineiti commented on crypto_secretstream/src/lib.rs
> +//! a nonce, generated by Alice, which is taken into account during encryption
```suggestion
//! An important part of the encryption is the use of a unique nonce.
//! If for a given key two different messages are sent with the same nonce, the key
//! can be easily calculated. But the nonce doesn't need to be secret. So Alice appends 
//! a random nonce to the first message. The encryption then uses this nonce to 
//! encrypt the message.
```

2021-07-30 10:48 UTC, ineiti commented on crypto_secretstream/src/nonce.rs
> +    pub const SIZE: usize = 24;
Same here - can't you take it from the ChaCha20 crate?

2021-07-30 10:50 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +const KEY: [u8; Key::SIZE] = [
Then add a link to where they come from.

2021-07-30 10:51 UTC, ineiti commented on crypto_secretstream/tests/lib.rs
> +
Did I remove your answer here? Sorry!

2021-07-30 14:53 UTC, tharvik commented on crypto_secretstream/src/lib.rs
> +//! a nonce, generated by Alice, which is taken into account during encryption
Not really, the nonce avoid reordering/replaying messages, not divulging the key.
I'm trying to not go into too much cryptographic depth for the introduction, [as done in the introduction to `crypto_box`](https://docs.rs/crypto_box/0.6.1/crypto_box/#introduction).

2021-07-30 14:56 UTC, tharvik commented on crypto_secretstream/src/pull.rs
> +    /// Decrypt a pushed message, with its associated data
> This should mention that it creates a new buffer.

Done.

> Rust-newbie question: why does it take an array of `u8` but returns a `Vec<u8>`?

It's not really rust specific, it's more related to how to write precises functions: be the less specific for inputs, and the most precise for outputs. In fact, `&Vec` is `&[u8]`, but as we allocate a `Vec` inside it, we can use the full type.

2021-07-30 15:23 UTC, tharvik commented on crypto_secretstream/src/key.rs
> +    pub const SIZE: usize = 32;
I need to `generate` it easily (and clear it from memory), so using a dedicated type is needed.

Exposing `chacha20poly1305::Key` does make the notation a bit heavier but that's not a real issue.
```rust
let key = chacha20poly1305::Key::from(KEY);
let mut push_stream = PushStream::init(&mut rand_core::OsRng, Key::from(key));
```
instead of
```rust
let mut push_stream = PushStream::init(&mut rand_core::OsRng, Key::from(KEY));
```

2021-07-30 15:28 UTC, tharvik commented on crypto_secretstream/src/nonce.rs
> +    pub const SIZE: usize = 24;
No, I can't, I need to have to access the size to extract the nonce from the ciphertext and to ensure that it wrap around in `increment`.

2021-07-30 15:35 UTC, tharvik commented on crypto_secretstream/tests/lib.rs
> +
Most of theses tests are blackbox tests, or are using [tags](https://doc.libsodium.org/secret-key_cryptography/secretstream#usage) or rekeying which I don't support currently.
I'll have to check with upstream if that's alright for them (which I think it is as they don't support that either in their AEAD).

2021-07-30 15:38 UTC, tharvik commented
> I would really like to have an integration test with libsodium here.

So, libsodium add a counter in the header, to rekey regularly, which is not what I implemented currently. I've started a bit to look into it at https://github.com/c4dt/nacl-compat/tree/test-stream-with-sodiumoxide
I think that first pushing this version upstream will already generate a bunch of comments and then we can add full libsodium compatibility.

2021-07-30 16:02 UTC, tharvik commented on crypto_secretstream/Cargo.toml
> +rand_core = { version = "0.6", features = ["std"] }
* `rand` is for generating randomness, such as via `rand::random::<u64>` and creating RNGs.
  It uses and exposes `rand_core` and should be uses by application rather than library.
* `rand_core` is providing traits for randomness, so that the library doesn't
  need to actually create a RNG itself but can use on.

2021-07-31 14:25 UTC, ineiti commented
> I think that first pushing this version upstream will already generate a bunch of comments and then we can add full libsodium compatibility.

Well, the repo is called nacl-compat. So if the PR is not compatible with nacl, then it's not the correct repo.

I prefer if we open a PR that is actually compatible with libnacl. I knew this would be more than 2-3 days, this is why I hesitated in the first place...

2021-08-19 15:56 UTC, tharvik commented
We have now full compatiblity with libsodium, tell me what you think :)

2021-08-23 09:29 UTC, ineiti reviewed
Very nice - didn't dive into the implementation yet. Some questions and remarks:

- are all tags supported now?
- let's discuss what documentation it needs and where it should be put
- are there shortcuts that should be documented?

2021-08-23 09:29 UTC, ineiti commented on crypto_secretstream/README.md
> +providing an [AEAD] using [chacha20] and [poly1305].
This needs a little bit more explanation wrt:
- that it only depends on RustCrypto
- that it's been tested against libnacl (where from?)
- an example how to use it
- things to take care of

2021-08-23 09:29 UTC, ineiti commented on crypto_secretstream/src/header.rs
> +/// Incipit of the secret stream, can be send as cleartext.
s/Incipit/Header/ ? Or is `Incipit` some official word I don't know (yet) about?

2021-08-23 09:29 UTC, ineiti commented on crypto_secretstream/src/stream.rs
> +impl Stream {
Needs some documentation.

2021-08-23 11:53 UTC, tharvik commented on crypto_secretstream/README.md
> +providing an [AEAD] using [chacha20] and [poly1305].
I tried to be as close to the other RustCrypto's readme, which [are](https://github.com/RustCrypto/nacl-compat/tree/master/crypto_box) [quite](https://github.com/RustCrypto/AEADs/tree/master/chacha20poly1305) [small](https://github.com/RustCrypto/stream-ciphers/tree/master/rabbit) and rust oriented.

Most of the "real" documentation is done in `src/lib.rs`.

2021-08-23 11:55 UTC, tharvik commented on crypto_secretstream/src/header.rs
> +/// Incipit of the secret stream, can be send as cleartext.
Nope, nothing special about it; it is simply weird for me to write "Header" as documentation for well, a struct called "Header", it doesn't add much information. So I try to vary. Was it confusing?

2021-08-23 12:06 UTC, tharvik commented
> * are all tags supported now?

Yep, "Rekey" is the only one requiring special handling. "Final" exists as a marker for end of communcation and is documented as clearing the keys from memory and disabling the stream but it isn't implemented in libsodium (:

> * let's discuss what documentation it needs and where it should be put

As for the other RustCrypto's crates, via the rust websites, on docs.rs

> * are there shortcuts that should be documented?

Nope, everything should work, it is bit per bit the same stream generated.
There is a single thing that I haven't tested, namely checking the auto-rekeying which would be nice to validate, but I need to overflow an u32 for that, and that takes a long time. Let's talk about finding a way around it next time.

2021-08-24 11:33 UTC, ineiti commented on crypto_secretstream/src/header.rs
> +/// Incipit of the secret stream, can be send as cleartext.
I had to look it up ;)

And it's `can be sent`

2021-08-24 11:44 UTC, tharvik commented on crypto_secretstream/src/header.rs
> +/// Incipit of the secret stream, can be send as cleartext.
Thanks for the review :)

2021-08-25 07:02 UTC, ineiti approved these changes

2021-08-25 10:26 UTC, tharvik commented
Upstreaming at https://github.com/RustCrypto/nacl-compat/pull/4

2021-08-25 10:26 UTC, closed without merging